/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadorabasica2numeros;

import javax.swing.JOptionPane;

/**
 *
 * @author Mario Santos
 */
public class CalculadoraBASICA2Numeros extends javax.swing.JFrame {
    String Valor1="";
    String Valor2="";
    String Op="";
    /**
     * Creates new form CalculadoraBASICA
     */
    public CalculadoraBASICA2Numeros() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        operacion = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        txoperacion = new javax.swing.JTextField();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        div = new javax.swing.JButton();
        mult = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        igual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        operacion.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        operacion.setForeground(new java.awt.Color(153, 153, 153));
        operacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(operacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 48, 20, 20));

        cerrar.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("X");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 0, 36, 23));

        txoperacion.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txoperacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txoperacion.setText("0");
        txoperacion.setEnabled(false);
        jPanel1.add(txoperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, 180, -1));

        siete.setText("7");
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });
        jPanel1.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, -1, -1));

        ocho.setText("8");
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });
        jPanel1.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 118, -1, -1));

        nueve.setText("9");
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });
        jPanel1.add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 118, -1, -1));

        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        jPanel1.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 147, -1, -1));

        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        jPanel1.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 147, -1, -1));

        cuatro.setText("4");
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        jPanel1.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, -1));

        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        jPanel1.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 176, -1, -1));

        dos.setText("2");
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        jPanel1.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 176, -1, -1));

        uno.setText("1");
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        jPanel1.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, -1, -1));

        cero.setText("0");
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });
        jPanel1.add(cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, 129, -1));

        limpiar.setText("C");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, 129, -1));

        div.setText("/");
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        jPanel1.add(div, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 89, 41, -1));

        mult.setText("*");
        mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multActionPerformed(evt);
            }
        });
        jPanel1.add(mult, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 118, 41, -1));

        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });
        jPanel1.add(menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 147, 41, -1));

        mas.setText("+");
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });
        jPanel1.add(mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 176, 40, -1));

        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        jPanel1.add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 205, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        cerrar.setForeground(java.awt.Color.red);
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        cerrar.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_cerrarMouseExited
    
    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        if(operacion.getText().equals("")){
            txoperacion.setText("2");
            Valor1=Valor1 + txoperacion.getText();
            txoperacion.setText(Valor1);
        }else{
            if(operacion.getText().equals("+")||operacion.getText().equals("-")||operacion.getText()=="*"||operacion.getText()=="/"){
                txoperacion.setText("7");
                Valor2=Valor2 + txoperacion.getText();
                txoperacion.setText(Valor2);
            }
        }
    }//GEN-LAST:event_sieteActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        if(operacion.getText().equals("")){
            txoperacion.setText("8");
            Valor1=Valor1 + txoperacion.getText();
            txoperacion.setText(Valor1);
        }else{
            if(operacion.getText().equals("+")||operacion.getText().equals("-")||operacion.getText()=="*"||operacion.getText()=="/"){
                txoperacion.setText("8");
                Valor2=Valor2 + txoperacion.getText();
                txoperacion.setText(Valor2);
            }
        }
    }//GEN-LAST:event_ochoActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        if(operacion.getText().equals("")){
            txoperacion.setText("9");
            Valor1=Valor1 + txoperacion.getText();
            txoperacion.setText(Valor1);
        }else{
            if(operacion.getText().equals("+")||operacion.getText().equals("-")||operacion.getText()=="*"||operacion.getText()=="/"){
                txoperacion.setText("9");
                Valor2=Valor2 + txoperacion.getText();
                txoperacion.setText(Valor2);
            }
        }
    }//GEN-LAST:event_nueveActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        if(operacion.getText().equals("")){
            txoperacion.setText("6");
            Valor1=Valor1 + txoperacion.getText();
            txoperacion.setText(Valor1);
        }else{
            if(operacion.getText().equals("+")||operacion.getText().equals("-")||operacion.getText()=="*"||operacion.getText()=="/"){
                txoperacion.setText("6");
                Valor2=Valor2 + txoperacion.getText();
                txoperacion.setText(Valor2);
            }
        }
    }//GEN-LAST:event_seisActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        if(operacion.getText().equals("")){
            txoperacion.setText("5");
            Valor1=Valor1 + txoperacion.getText();
            txoperacion.setText(Valor1);
        }else{
            if(operacion.getText().equals("+")||operacion.getText().equals("-")||operacion.getText()=="*"||operacion.getText()=="/"){
                txoperacion.setText("5");
                Valor2=Valor2 + txoperacion.getText();
                txoperacion.setText(Valor2);
            }
        }
    }//GEN-LAST:event_cincoActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        if(operacion.getText().equals("")){
            txoperacion.setText("4");
            Valor1=Valor1 + txoperacion.getText();
            txoperacion.setText(Valor1);
        }else{
            if(operacion.getText().equals("+")||operacion.getText().equals("-")||operacion.getText()=="*"||operacion.getText()=="/"){
                txoperacion.setText("4");
                Valor2=Valor2 + txoperacion.getText();
                txoperacion.setText(Valor2);
            }
        }
    }//GEN-LAST:event_cuatroActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        if(operacion.getText().equals("")){
            txoperacion.setText("3");
            Valor1=Valor1 + txoperacion.getText();
            txoperacion.setText(Valor1);
        }else{
            if(operacion.getText().equals("+")||operacion.getText().equals("-")||operacion.getText()=="*"||operacion.getText()=="/"){
                txoperacion.setText("3");
                Valor2=Valor2 + txoperacion.getText();
                txoperacion.setText(Valor2);
            }
        }
    }//GEN-LAST:event_tresActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        if(operacion.getText().equals("")){
            txoperacion.setText("2");
            Valor1=Valor1 + txoperacion.getText();
            txoperacion.setText(Valor1);
        }else{
            if(operacion.getText().equals("+")||operacion.getText().equals("-")||operacion.getText()=="*"||operacion.getText()=="/"){
                txoperacion.setText("2");
                Valor2=Valor2 + txoperacion.getText();
                txoperacion.setText(Valor2);
            }
        }
    }//GEN-LAST:event_dosActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        if(operacion.getText().equals("")){
            txoperacion.setText("1");
            Valor1=Valor1 + txoperacion.getText();
            txoperacion.setText(Valor1);
        }else{
            if(operacion.getText().equals("+")||operacion.getText().equals("-")||operacion.getText()=="*"||operacion.getText()=="/"){
                txoperacion.setText("1");
                Valor2=Valor2 + txoperacion.getText();
                txoperacion.setText(Valor2);
            }
        }
    }//GEN-LAST:event_unoActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        if(operacion.getText().equals("")){
            txoperacion.setText("0");
            Valor1=Valor1 + txoperacion.getText();
            txoperacion.setText(Valor1);
        }else{
            if(operacion.getText().equals("+")||operacion.getText().equals("-")||operacion.getText()=="*"||operacion.getText()=="/"){
                txoperacion.setText("0");
                Valor2=Valor2 + txoperacion.getText();
                txoperacion.setText(Valor2);
            }
        }
    }//GEN-LAST:event_ceroActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        txoperacion.setText("0");
        operacion.setText("");
        Op="";
        Valor1="";
        Valor2="";
    }//GEN-LAST:event_limpiarActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        operacion.setText("/");
        txoperacion.setText("0");
        Op="/";
    }//GEN-LAST:event_divActionPerformed

    private void multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multActionPerformed
        operacion.setText("*");
        txoperacion.setText("0");
        Op="*";
    }//GEN-LAST:event_multActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        operacion.setText("-");
        txoperacion.setText("0");
        Op="-";
    }//GEN-LAST:event_menosActionPerformed

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        operacion.setText("+");
        txoperacion.setText("0");
        Op="+";
    }//GEN-LAST:event_masActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        operacion.setText("=");
        if(Op=="+"){
            int v1 = Integer.parseInt(Valor1);
            int v2 = Integer.parseInt(Valor2);
            
            int suma=v1+v2;
            String Suma=String.valueOf(suma);
            
            txoperacion.setText(Suma);
        }else{
           if(Op=="-"){
                int v1 = Integer.parseInt(Valor1);
                int v2 = Integer.parseInt(Valor2);
            
                int resta=v1-v2;
                String Resta=String.valueOf(resta);
            
                txoperacion.setText(Resta);
            }else{
                if(Op=="*"){
                    int v1 = Integer.parseInt(Valor1);
                    int v2 = Integer.parseInt(Valor2);
            
                    int mult=v1*v2;
                    String Mult=String.valueOf(mult);
            
                    txoperacion.setText(Mult);
                }else{
                    if(Op=="/"){
                        int v1 = Integer.parseInt(Valor1);
                        int v2 = Integer.parseInt(Valor2);
            
                        int div=v1/v2;
                        String Div=String.valueOf(div);
            
                        txoperacion.setText(Div);
                    }
                }
           }
        }
    }//GEN-LAST:event_igualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBASICA2Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBASICA2Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBASICA2Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBASICA2Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraBASICA2Numeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cero;
    private javax.swing.JLabel cerrar;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton div;
    private javax.swing.JButton dos;
    private javax.swing.JButton igual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    private javax.swing.JButton mult;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JLabel operacion;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton tres;
    private javax.swing.JTextField txoperacion;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}
